"""str->int TGUser and Chat table pk

Revision ID: 69d05c0940e2
Revises: 
Create Date: 2024-06-15 21:16:17.746153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d05c0940e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.create_table('keyword',
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_id'), 'keyword', ['id'], unique=False)
    op.create_index(op.f('ix_keyword_keyword'), 'keyword', ['keyword'], unique=True)
    op.create_table('keyword_group',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_group_id'), 'keyword_group', ['id'], unique=False)
    op.create_table('tg_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_user_id'), 'tg_user', ['id'], unique=False)
    op.create_table('keyword_group_keyword_map',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['keyword_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_group_keyword_map_group_id'), 'keyword_group_keyword_map', ['group_id'], unique=False)
    op.create_index(op.f('ix_keyword_group_keyword_map_id'), 'keyword_group_keyword_map', ['id'], unique=False)
    op.create_index(op.f('ix_keyword_group_keyword_map_keyword_id'), 'keyword_group_keyword_map', ['keyword_id'], unique=False)
    op.create_table('keyword_map',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tg_user_id'], ['tg_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_map_created_at'), 'keyword_map', ['created_at'], unique=False)
    op.create_index(op.f('ix_keyword_map_id'), 'keyword_map', ['id'], unique=False)
    op.create_index(op.f('ix_keyword_map_keyword_id'), 'keyword_map', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_map_tg_user_id'), 'keyword_map', ['tg_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_map_tg_user_id'), table_name='keyword_map')
    op.drop_index(op.f('ix_keyword_map_keyword_id'), table_name='keyword_map')
    op.drop_index(op.f('ix_keyword_map_id'), table_name='keyword_map')
    op.drop_index(op.f('ix_keyword_map_created_at'), table_name='keyword_map')
    op.drop_table('keyword_map')
    op.drop_index(op.f('ix_keyword_group_keyword_map_keyword_id'), table_name='keyword_group_keyword_map')
    op.drop_index(op.f('ix_keyword_group_keyword_map_id'), table_name='keyword_group_keyword_map')
    op.drop_index(op.f('ix_keyword_group_keyword_map_group_id'), table_name='keyword_group_keyword_map')
    op.drop_table('keyword_group_keyword_map')
    op.drop_index(op.f('ix_tg_user_id'), table_name='tg_user')
    op.drop_table('tg_user')
    op.drop_index(op.f('ix_keyword_group_id'), table_name='keyword_group')
    op.drop_table('keyword_group')
    op.drop_index(op.f('ix_keyword_keyword'), table_name='keyword')
    op.drop_index(op.f('ix_keyword_id'), table_name='keyword')
    op.drop_table('keyword')
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
