"""report table nullable

Revision ID: c439d73cd0b4
Revises: 59b300dcfd01
Create Date: 2024-06-16 00:36:35.462470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c439d73cd0b4'
down_revision: Union[str, None] = '59b300dcfd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword_map_report', 'keyword',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('keyword_map_report', 'groups',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('keyword_map_report', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('keyword_map_report', 'chat_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword_map_report', 'chat_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('keyword_map_report', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('keyword_map_report', 'groups',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('keyword_map_report', 'keyword',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
