"""report table add 

Revision ID: 59b300dcfd01
Revises: 69d05c0940e2
Create Date: 2024-06-15 22:45:35.976731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b300dcfd01'
down_revision: Union[str, None] = '69d05c0940e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_map_report',
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('groups', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('chat_title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_map_report_created_at'), 'keyword_map_report', ['created_at'], unique=False)
    op.create_index(op.f('ix_keyword_map_report_id'), 'keyword_map_report', ['id'], unique=False)
    op.alter_column('chat', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_keyword_map_report_id'), table_name='keyword_map_report')
    op.drop_index(op.f('ix_keyword_map_report_created_at'), table_name='keyword_map_report')
    op.drop_table('keyword_map_report')
    # ### end Alembic commands ###
