"""init tables

Revision ID: 8a1eddf37464
Revises: 
Create Date: 2024-05-22 23:38:58.024205

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8a1eddf37464'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('tg_user',
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_index(op.f('ix_tg_user_user_id'), 'tg_user', ['user_id'], unique=False)

    op.create_table('keyword_map',
                    sa.Column('map_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"),
                              nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['tg_user.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('map_id')
                    )
    op.create_index(op.f('ix_keyword_map_map_id'), 'keyword_map', ['map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_map_map_id'), table_name='keyword_map')
    op.drop_table('keyword_map')
    op.drop_index(op.f('ix_tg_user_user_id'), table_name='tg_user')
    op.drop_table('tg_user')
    # ### end Alembic commands ###
